# This kernel package is a minimal spec with kernel + overlayfs modules to allow mounting overlays from livecd
unpack: true
includes:
# Kernel
- /boot$|/boot/.*
- /lib$
- /lib/modules$
- /lib/modules/5.4.0-sabayon$
- /lib/modules/5.4.0-sabayon/modules.*
- /lib/modules/5.4.0-sabayon/source
- /lib/modules/5.4.0-sabayon/build

# OverlayFS
- /lib/modules/5.4.0-sabayon/kernel$
- /lib/modules/5.4.0-sabayon/kernel/fs$
- /lib/modules/5.4.0-sabayon/kernel/fs/mbcache.ko
- /lib/modules/5.4.0-sabayon/kernel/fs/overlayfs$
- /lib/modules/5.4.0-sabayon/kernel/fs/overlayfs/.*
- /lib/modules/5.4.0-sabayon/kernel/lib$
- /lib/modules/5.4.0-sabayon/kernel/lib/.*

# USB
- /lib/modules/5.4.0-sabayon/kernel$
- /lib/modules/5.4.0-sabayon/kernel/drivers$
- /lib/modules/5.4.0-sabayon/kernel/drivers/usb$
- /lib/modules/5.4.0-sabayon/kernel/drivers/usb/.*
- /lib/modules/5.4.0-sabayon/kernel/drivers/usb/storage$
- /lib/modules/5.4.0-sabayon/kernel/drivers/usb/storage/.*
- /lib/modules/5.4.0-sabayon/kernel/drivers/usb/host$
- /lib/modules/5.4.0-sabayon/kernel/drivers/usb/host/.*
- /lib/modules/5.4.0-sabayon/kernel/drivers/usb/common$
- /lib/modules/5.4.0-sabayon/kernel/drivers/usb/common/.*

image: sabayon/base-amd64
env:
- ACCEPT_LICENSE=*
- LC_ALL=en_US.UTF-8
prelude:
- chmod a+x ./override_mirror.sh && ./override_mirror.sh
- equo up
- equo i app-portage/layman dev-vcs/git sys-devel/gcc
- equo i sys-kernel/linux-sabayon --onlydeps
- equo cleanup
# Prepare emerge stuff
- emerge-webrsync
- layman -f && eval 'echo "y" | layman -f -a sabayon' && eval 'echo "y" | layman -a sabayon-distro'
- eselect profile set "default/linux/amd64/17.1/desktop"
- gcc-config x86_64-pc-linux-gnu-8.2.0
steps:
- source /etc/profile && emerge =sys-kernel/linux-sabayon-{{ ( index .Values.labels "original.package.version" ) }}
