image: "quay.io/mocaccino/micro:master"

steps:
- | 
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   mkdir -p /${PACKAGE_NAME}/usr/bin && \
   cp -rfv mocaccino-dracut  /${PACKAGE_NAME}/usr/bin/ && \
   chmod +x /${PACKAGE_NAME}/usr/bin/mocaccino-dracut
