requires:
- category: "kernel-5.8"
  name: "sabayon-sources"
  version: ">=0"
package_dir: /zfs-kmod
includes:
- /lib$|/lib/modules$
- /lib/modules/.*
env:
- ACCEPT_LICENSE=*
- LC_ALL=en_US.UTF-8
- JOBS=3
- PKGDIR=/usr/portage/packages
prelude:
- |
  equo i sys-fs/zfs-kmod --onlydeps --relaxed && \
  equo cleanup
# Ensure that sources are in a good status
- cd /usr/src/ && ls -l && rm linux && ln -s linux-5.8.0-sabayon linux
- cd /usr/src/linux && make mrproper && cp sabayon/config/sabayon-amd64.config .config && make prepare
steps:
- |
  source /etc/profile && \
  cd /usr/src/linux && make -j $JOBS modules && \
  emerge =sys-fs/${PACKAGE_NAME}-${PACKAGE_VERSION%\+*} --nodeps && \
  make clean && \
  quickpkg sys-${PACKAGE_CATEGORY}/${PACKAGE_NAME} && \
  mkdir /${PACKAGE_NAME} && mkdir -p /tmp/data && \
  qtbz2 -d /tmp/data/ ${PKGDIR}/sys-fs/${PACKAGE_NAME}-${PACKAGE_VERSION%\+*}.tbz2 && \
  tar xvjf /tmp/data/${PACKAGE_NAME}-${PACKAGE_VERSION%\+*}.tar.bz2 -C /${PACKAGE_NAME} && \
  rm -rf /tmp/data

