steps:
- bash build.sh
env:
- PREFIX={{.Values.prefix}}
- SUFFIX={{.Values.suffix}}
- ARCH={{.Values.arch}}
- KERNEL_PREFIX=kernel-vanilla
package_dir: /luetbuild/modules
requires:
- name: "mocaccino-full"
  category: "kernel"
  version: ">=0"
