requires:
- category: "kernel"
  name: "linux-firmware"
  version: ">=0"
package_dir: /linux-firmware
steps:
- quickpkg sys-${PACKAGE_CATEGORY}/${PACKAGE_NAME/-portage/}
- mkdir -p /tmp/data
- qtbz2 -d /tmp/data/ /var/cache/portage/packages/sys-${PACKAGE_CATEGORY}/${PACKAGE_NAME/-portage/}-${PACKAGE_VERSION%\+*}.tbz2
- mkdir -p /${PACKAGE_NAME}/var/db/pkg/sys-${PACKAGE_CATEGORY}/${PACKAGE_NAME/-portage/}-${PACKAGE_VERSION%\+*}/
- qxpak -x -d /${PACKAGE_NAME}/var/db/pkg/sys-${PACKAGE_CATEGORY}/${PACKAGE_NAME/-portage/}-${PACKAGE_VERSION%\+*}/ /tmp/data/${PACKAGE_NAME/-portage/}-${PACKAGE_VERSION%\+*}.xpak

# We want /etc/portage savedconfig
- tar xvjf /tmp/data/${PACKAGE_NAME/-portage/}-${PACKAGE_VERSION%\+*}.tar.bz2 -C /${PACKAGE_NAME}
- rm -rf /${PACKAGE_NAME}/lib/
- rm -rf /tmp/data
