unpack: true
includes:
# Kernel
- /boot$|/boot/.*
- /lib$
- /lib/modules$
- /lib/modules/5.4.0-sabayon$
- /lib/modules/5.4.0-sabayon/.*
- /lib/modprobe.d$|/lib/modprobe.d/.*
image: sabayon/base-amd64
prelude:
- chmod a+x ./override_mirror.sh && ./override_mirror.sh
- equo up
steps:
- ACCEPT_LICENSE=* equo i sys-kernel/linux-sabayon:${PACKAGE_CATEGORY/kernel-/}
