unpack: true
includes:
# Kernel
- /boot$|/boot/.*
- /lib$
- /lib/firmware$|/lib/firmware/.*
- /lib/modules$|/lib/modules/.*
- /lib/modprobe.d$|/lib/modprobe.d/.*
image: sabayon/base-amd64
prelude:
- equo up
steps:
- ACCEPT_LICENSE=* equo i sys-kernel/linux-sabayon:${PACKAGE_VERSION}