image: "funtoo/stage3-generic_64:2020-07-06"
package_dir: /linux-firmware
env:
- JOBS=3
prelude:
- eqo sync
- epro list
- emerge -j ${JOBS} --onlydeps sys-${PACKAGE_CATEGORY}/${PACKAGE_NAME}
steps:
- emerge --nodeps -t sys-${PACKAGE_CATEGORY}/${PACKAGE_NAME}
- quickpkg sys-${PACKAGE_CATEGORY}/${PACKAGE_NAME}
- mkdir -p /tmp/data
- qtbz2 -d /tmp/data/ /var/cache/portage/packages/sys-${PACKAGE_CATEGORY}/${PACKAGE_NAME}-${PACKAGE_VERSION%\+*}.tbz2

- tar xvjf /tmp/data/${PACKAGE_NAME}-${PACKAGE_VERSION%\+*}.tar.bz2 -C /${PACKAGE_NAME}
# Drop portage savedconfig
- rm -rf /${PACKAGE_NAME}/etc

